spring:
  application:
    name: springboot-jpa N-plus-One
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpa?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true
        format_sql: true
    open-in-view: true
    show-sql: true
